apiVersion: v1
kind: Service
metadata:
  name: photo-service
  namespace: dev

spec:
  selector:
    app: photo-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photo-service
  template:
    metadata:
      labels:
        app: photo-service
    spec:
      containers:
      - name: photo-service
        image: gitlab-df-registry.imt-atlantique.fr/devops-s24/devops-app-s24-13/photo-service:8bd4d493
        env:
        - name: DATABASE_NAME
          value: "devops-s24-13-photographer-db"
        - name: PHOTOGRAPHER_HOST
          value: "photographer-service"
        - name: AUTH_DATABASE_NAME
          value: "devops-s24-13-photographer-db"
        - name: MONGO_HOST
          value: "mongo.cloud.imta.fr"
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo
              key: password
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
