apiVersion: v1
kind: Service
metadata:
  name: photographer-service
  namespace: CHANGE_NAMESPACE

spec:
  selector:
    app: photographer-service
  ports:
  - protocol: TCP
    port: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: photographer-service
  namespace: CHANGE_NAMESPACE

spec:
  replicas: 1
  selector:
    matchLabels:
      app: photographer-service
  template:
    metadata:
      labels:
        app: photographer-service
    spec:
      containers:
      - name: photographer-service
        image: gitlab-df-registry.imt-atlantique.fr/devops-s24/devops-app-s24-13/photographer:fc2d9de9 
        env:
        - name: DATABASE_NAME
          value: "devops-s24-13-photographer-db"
        - name: AUTH_DATABASE_NAME
          value: "devops-s24-13-photographer-db"
        - name: MONGO_HOST
          value: "mongo.cloud.imta.fr"
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo
              key: password
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
